word = input()
word = word.replace('c=', 'o')
word = word.replace('c-', 'o')
word = word.replace('dz=', 'o')
word = word.replace('d-', 'o')
word = word.replace('lj', 'o')
word = word.replace('nj', 'o')
word = word.replace('s=', 'o')
word = word.replace('z=', 'o')
print(len(word))